name: Daily Matches Check

on:
  schedule:
    # Runs at 11:00 UTC every day. Adjust cron time as needed.
    - cron: '0 11 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Specify Python version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script and capture output
        id: run-script
        run: |
          python matches_script.py > matches_output.txt
          echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
          cat matches_output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug output (optional)
        run: |
          echo "Generated output content:"
          cat matches_output.txt
          echo "Environment variable content:"
          echo "${{ env.SCRIPT_OUTPUT }}"

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: scoutinglk123@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Daily Matches Check (${{ github.run_id }})
          to: scoutinglk123@gmail.com
          from: GitHub Actions Runner <scoutinglk123@gmail.com>
          body: ${{ env.SCRIPT_OUTPUT }}
          secure: true
