# .github/workflows/weekly_debutants.yml
name: Weekly Debutants Report

on:
  schedule:
    # Runs at 08:00 UTC every Monday. Adjust cron time as needed.
    # See: https://crontab.guru/
    - cron: '0 8 * * 1'
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  run-r-script:
    runs-on: ubuntu-latest # Use a Linux runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Use the latest release of R

      - name: Install R dependencies
        run: |
          # Install packages explicitly for clarity in Actions
          install.packages(c("worldfootballR", "dplyr"), dependencies = TRUE)
        shell: Rscript {0}

      - name: Run R script and capture output
        run: Rscript debutants_script.R > debutants_output.txt 2>&1

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465 # Gmail uses port 465 for SSL
          username: scoutinglk123@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }} # Use the secret!
          subject: Weekly Debutants Report (${{ github.run_id }})
          body_file: debutants_output.txt # Attach the script's output as the body
          to: scoutinglk123@gmail.com
          from: GitHub Actions Runner <scoutinglk123@gmail.com> # 'Name <email>' format
          secure: true # Use true for SSL (port 465)
