name: Weekly Debutants Report
on:
  schedule:
    - cron: '0 4 * * 3'
  workflow_dispatch:
jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      - name: Install CRAN packages
        run: |
          R -e "install.packages(c('remotes', 'dplyr'), repos = 'https://cloud.r-project.org')"
          
      - name: Install worldfootballR
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          R -e "remotes::install_github('JaseZiv/worldfootballR', dependencies = TRUE, upgrade = 'never')"
          
      - name: Run R script with error checking
        id: run-script
        run: |
          # Run script and capture output and exit code
          Rscript debutants_script.R > output.txt
          EXIT_CODE=$?
          echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # Check for errors in output
          if grep -q "ERROR" output.txt; then
            echo "ERROR_DETECTED=true" >> $GITHUB_ENV
            echo "::error::Error detected in league data - will retry"
            exit 1
          elif [ $EXIT_CODE -ne 0 ]; then
            echo "ERROR_DETECTED=true" >> $GITHUB_ENV
            echo "::error::Script failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          else
            echo "ERROR_DETECTED=false" >> $GITHUB_ENV
          fi
          
      - name: Retry on error
        if: ${{ env.ERROR_DETECTED == 'true' }}
        run: |
          echo "Retrying script..."
          Rscript debutants_script.R > output.txt
          EXIT_CODE=$?
          if grep -q "ERROR" output.txt || [ $EXIT_CODE -ne 0 ]; then
            echo "::error::Error still present after retry - aborting"
            exit 1
          fi
          echo "SCRIPT_OUTPUT<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Send email report
        if: ${{ env.ERROR_DETECTED != 'true' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: scoutinglk123@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Weekly Debutants Report (${{ github.run_id }})
          to: scoutinglk123@gmail.com
          from: GitHub Actions Runner
          body: ${{ env.SCRIPT_OUTPUT }}
          secure: true
