name: Weekly Debutants Report
on:
  schedule:
    - cron: '0 4 * *3'
  workflow_dispatch:
jobs:
  run-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      - name: Install CRAN packages
        run: |
          R -e "install.packages(c('remotes', 'dplyr', 'usethis', 'rcmdcheck', 'rversions', 'pkgdown', 'urlchecker'), repos = 'https://cloud.r-project.org')"
          
      - name: Install devtools
        run: |
          R -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"
          
      - name: Install worldfootballR
        run: |
          R -e "remotes::install_github('JaseZiv/worldfootballR', dependencies = TRUE, upgrade = 'never')"
          
      - name: Run R script
        run: Rscript debutants_script.R > debutants_output.txt
        
      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: scoutinglk123@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Weekly Debutants Report (${{ github.run_id }})
          body_file: debutants_output.txt
          to: scoutinglk123@gmail.com
          from: GitHub Actions Runner
          secure: true
