# .github/workflows/weekly_debutants.yml
name: Weekly Debutants Report

on:
  schedule:
    # Runs at 08:00 UTC every Monday. Adjust cron time as needed.
    # See: https://crontab.guru/
    - cron: '0 4 * * 3'
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  run-r-script:
    runs-on: ubuntu-latest # Use a Linux runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Use the latest release of R

      # --- MODIFIED INSTALLATION STEPS ---
      - name: Install system dependencies (if any needed by packages)
        run: |
          # Add commands here if packages like devtools or its dependencies need system libraries
          # e.g., sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          echo "No specific system dependencies added for now, but may be needed if install still fails."
        # Optional: Add if you encounter system library issues during package install

      - name: Install Core R Dependencies (devtools, its deps, dplyr)
        run: |
          # Explicitly list missing dependencies identified in the previous run's error log
          # Also include devtools itself and other script dependencies like dplyr
          install.packages(c(
            'usethis', 
            'pkgdown', 
            'rcmdcheck', 
            'rversions', 
            'urlchecker',
            'devtools',  # Now install devtools
            'dplyr'      # Include other direct dependencies
          ), dependencies = TRUE) # dependencies=TRUE helps catch further nested dependencies
        shell: Rscript {0}

      - name: Install worldfootballR from GitHub
        run: |
          # This step should now succeed because devtools and its dependencies are installed
          devtools::install_github("JaseZiv/worldfootballR", dependencies = TRUE, upgrade = "never")
        shell: Rscript {0}
      # --- END OF MODIFIED STEPS ---

      - name: Run R script and capture output
        # Ensure your script doesn't try to re-install packages now
        run: Rscript debutants_script.R > debutants_output.txt

      - name: Send email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465 # Gmail uses port 465 for SSL
          username: scoutinglk123@gmail.com
          password: ${{ secrets.MAIL_PASSWORD }} # Use the secret!
          subject: Weekly Debutants Report (${{ github.run_id }})
          body_file: debutants_output.txt # Attach the script's output as the body
          to: scoutinglk123@gmail.com
          from: GitHub Actions Runner <scoutinglk123@gmail.com> # 'Name <email>' format
          secure: true # Use true for SSL (port 465)
